export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_SINGLE_EMPLOYEE = "GET_SINGLE_EMPLOYEE";
export const POST_EMPLOYEE = "POST_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
